# Docker Compose is used for spinning up the local-da docker container along with the GM container.

services:
  artroll:
    container_name: artroll
    # The build config can be used for debugging and testing changes to the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.lazy
      args:
        - ROLLKIT_VERSION=v0.13.7
        - IGNITE_VERSION=v28.4.0
        - DA_ADDRESS=http://localhost:7980
      tags:
        - ghcr.io/lazychain/artela-rollkit-lazy:v0.0.1-beta5

    # The image config can be used for running against published images
    # image: artelanetwork/rollkit:latest

    # Used for targetting localhost as if you were outside the container
    # network_mode: host

    ports:
      - "26657:26657"
      - "1317:1317"
      - "8545:8545"

    # Always pull the latest image
    pull_policy: always

    # The command config is used for launching the rollup once the Docker container is running
    # command: artrolld start --rollkit.aggregator --rollkit.da_address http://localhost:7980
    # command: "-f /dev/null"
    # entrypoint: /usr/bin/tail
    # tty: true
    environment:
      - DA_ADDRESS=http://local-da:7980
    depends_on:
      - local-da

  local-da:
    image: ghcr.io/rollkit/local-da:v0.2.1
    container_name: local-da
    ports:
      - "7980:7980"
